### ISSUE TITLE
Update knife tool to return FQDNs instead of IPs

### ISSUE THREAD

**Issue by mburns** [racker/dreadnot#138]
Currently, Dreadnot [wraps the `knife` command](https://github.com/racker/dreadnot/blob/master/lib/util/knife.js) to query Chef-Server to get values like the array of IPs to use for a given step.

We should tweak Dreadnot to return hostname / FQDNs instead of IP address. This way, when we `ssh $(ip) $(cmd)`, we'll be doing a DNS lookup.

I tried applying #137 manually, but it didn't appear to make a difference. CC @racker/rackspacemonitoringbombardiers

**Comment by rphillips** [comment]
@mburns check out https://github.com/racker/chef/pull/4693
