### ISSUE TITLE
Support Terminal escape codes

### ISSUE THREAD

**Issue by mburns** [racker/dreadnot#70]
Our formatted Chef outputs in color, which looks like garbage in Dreadnot:

![!screenshot](http://i.imgur.com/wUsy0Kr.png)

It should use a library to parse them and apply the right color.

Worst case, we could [strip things out](https://www.npmjs.com/package/strip-color)

**Comment by mburns** [comment]
Talked to @creationix about this. Might be able to convert the escape codes to HTML using an `npm` library.

**Comment by creationix** [comment]
I decided to do it in the browser since that's where the HTML table is rendered.

**Comment by creationix** [comment]
It's now deployed.
