### ISSUE TITLE
Allow end user to see systems in a deploy group

### ISSUE THREAD

**Issue by drenalin23** [racker/dreadnot#77]
For example - what servers am I going to be deploying to if I choose 'misc'?  
Could be a tooltip or small list under the name...

**Comment by mburns** [comment]
dry-run support exists in Dreadnot, but isn't used by our installations.

https://github.com/racker/chef/blob/master/site-cookbooks/ele-dreadnot/templates/default/dn-prod-settings.js.erb#L17
