### ISSUE TITLE
Deployment log does not show in Safari

### ISSUE THREAD

**Issue by bradgignac** [racker/dreadnot#8]
When viewing an in-progress deployment in Safari 5.1.1 on Max OS 10.6, the deployment log is not displayed. In my Javascript console, I see the following error:

```Error during WebSocket handshake: location mismatch: wss://reach-dreadnot.k1k.me/socket.io/1/websocket/1373491425311499637 != ws://reach-dreadnot.k1k.me/socket.io/1/websocket/1373491425311499637```

**Comment by jguice** [comment]
working fine here in Safari 8.0.4 (10600.4.10.7) and node 0.10.33...maybe this issue has expired? :)

**Comment by mburns** [comment]
Closing as fixed.
